experiment:
  folder_prefix: /var/tmp/tumorprofiler/
  subfolders: [raw, raw/raw_I, raw/raw_M, vsrs, derived, scripts]
  raw_data_immune: raw/raw_I
  raw_data_tumor:  raw/raw_M

IMC:
  allow_append_raw_data: True
  repo:
    source: https://github.com/BodenmillerGroup/tumorprofiler_imc.git
    branch: 'master'
    location: scripts

  metadata:
     I_panel_name: IMC_I_Panel.csv
     M_panel_name: IMC_M_Panel.csv
     ilastik_script: IMC_Segmentation_Parameters.ilp
     location: scripts

sMC:
  allow_append_raw_data: False
  repo:
    source: git@github.com:BodenmillerGroup/TumorProfiler.git
    branch: 'origin/PoC4'
    location: scripts

  metadata:
     location: scripts
